"""Adding Team Column To Player

Revision ID: 321b43d7f51b
Revises: f5a5962b1860
Create Date: 2022-07-31 23:11:06.695498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321b43d7f51b'
down_revision = 'f5a5962b1860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'team')
    # ### end Alembic commands ###
